stages:
  - clean
  - build
  - deploy
  - sonar

clean_elasticsearch:
  stage: clean
  tags:
    - c2mon
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - killall -q java || true
    - rm -Rf /tmp/es-cluster*

# Fully build and publish master branch
build_and_publish:
  stage: build
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean test -DskipDocker=true -Djavax.net.ssl.trustStore=${CACERTS} --settings settings.xml -Ddependencies.set.direct --debug -X
  except:
    - master
    - tags

build_docs:
  stage: build
  image: jekyll/builder:3.8.5
  tags: [docker]
  script:
    - cd docs
    - jekyll build --config "_config.yml,_overwrite_url.yml"
  artifacts:
    name: site
    when: on_success
    expire_in: 7 days
    untracked: true
    paths:
      - _site
  only:
    - master

trigger_build:
  stage: deploy
  tags: [c2mon]
  dependencies: []
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  dependencies:
    - build_docs
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - scp -o 'StrictHostKeyChecking no' -o 'GSSAPITrustDNS yes' -o 'GSSAPIDelegateCredentials yes' -B -r docs/_site/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch
  only:
    - master

sonar_preview:
  stage: sonar
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  tags: [c2mon]
  dependencies: []
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
