stages:
  - clean
  - build
  - deploy
  - sonar

clean_elasticsearch:
  type: clean
  script:
    - rm -Rf /tmp/elasticsearch-node

# Fully build and publish master branch
build_and_publish:
  type: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -U -B clean test -DskipDockerBuild -DskipDockerTag --settings settings.xml -Ddependencies.set.direct --debug -X
  except:
    - master
    
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  type: deploy
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - mvn -q -B clean package -pl :docs
    - scp -o 'StrictHostKeyChecking no' -B -r docs/target/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master
    
sonar_preview:
  type: sonar
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=https://en-ice-sonar.cern.ch -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master

quality_assurance:
  stage: sonar
  script:
    - mvn package dependency-check:aggregate sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=https://en-ice-sonar.cern.ch -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
