apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: c2mon-web
  name: c2mon-web
spec:
  replicas: 1
  selector:
    matchLabels:
      type: c2mon-web
  template:
    metadata:
      labels:
        type: c2mon-web
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: c2mon-client-properties
        name: c2mon-web
        image: cern/c2mon-web-ui:0.1.14-SNAPSHOT
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: c2mon-web
  name: c2mon-web
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31322
  type: NodePort
  selector:
    type: c2mon-web