apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      type: grafana
  template:
    metadata:
      labels:
        type: grafana
    spec:
      containers:
      - image: cern/c2mon-ext:grafana-6.1.2-c2mon-1.9.0
        name: grafana
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: grafana
  name: grafana
spec:
  ports:
    - name: grafana-default
      port: 3000
      targetPort: 3000
      nodePort: 31323
  type: NodePort
  selector:
    type: grafana