apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: c2mon-dev
  creationTimestamp: null
  labels:
    io.kompose.service: c2mon-web
  name: c2mon-web
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: c2mon-web
    spec:
      containers:
      - env:
        - name: C2MON_SERVER_ELASTICSEARCH_HOST
          value: http://es:9200
        - name: C2MON_CLIENT_JMS_URL
          value: tcp://mq:61616
        - name: C2MON_CLIENT_HISTORY_JDBC_URL
          value: jdbc:mysql://db/tim
        - name: C2MON_CLIENT_HISTORY_JDBC_USERNAME
          value: root
        - name: C2MON_CLIENT_HISTORY_JDBC_VALIDATION-QUERY
          value: SELECT 1
        name: c2mon-web
        image: cern/c2mon-web-ui
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: c2mon-dev
  creationTimestamp: null
  labels:
    io.kompose.service: c2mon-web
  name: c2mon-web
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31322
  type: NodePort
  selector:
    io.kompose.service: c2mon-web
---
