apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: c2mon-dev
  labels:
    io.kompose.service: daq
  name: daq
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: daq
    spec:
      containers:
      - image: cern/c2mon-daq:c2mon-daq-hostmetrics-0.0.4-SNAPSHOT
        name: daq
        env:
        - name: C2MON_DAQ_JMS_URL
          value: failover:tcp://mq:61616
        - name: C2MON_CLIENT_JMS_URL
          value: failover:tcp://mq:61616
        args: [ "-f", "P_HOST01" ]
---
