apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: mq
  name: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mq
  template:
    metadata:
      labels:
        type: mq
    spec:
      containers:
      - image: cern/c2mon-ext:activemq-5.15.6-c2mon-1.9.0
        name: mq
        ports:
        - containerPort: 61616
        - containerPort: 61614
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: c2mon-dev
  labels:
    type: mq
  name: mq
spec:
  ports:
    - name: activemq-default-tcp
      port: 61616
      targetPort: 61616
    - name: "61614"
      port: 61614
      targetPort: 61614
  selector:
    type: mq