site_name: C2MON
site_url: http://cern.ch/c2mon
docs_dir: ./src
site_dir: ./target
site_favicon: favicon.ico

theme_dir: ./theme
#theme: readthedocs

repo_url: https://gitlab.cern.ch/c2mon/c2mon
repo_name: CERN GitLab
edit_uri: blob/master/docs/src/

pages:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Overview:
    - 'overview.md'
    - Core Concepts:
      - 'core-concepts/index.md'
      - 'Process/Equipment': 'core-concepts/process-equipment.md'
      - 'core-concepts/tags.md'
      - 'core-concepts/supervision.md'
      - 'core-concepts/alarms.md'
      - 'Class/Device/Property': 'core-concepts/class-device-property.md'
  - User Guide:
    - 'user-guide/index.md'
    - Client API:
      - 'user-guide/client-api/index.md'
      - 'user-guide/client-api/subscribing.md'
      - 'user-guide/client-api/configuration.md'
      - 'user-guide/client-api/history.md'
    - DAQ API:
      - 'user-guide/daq-api/index.md'
      - 'user-guide/daq-api/DAQ_module_developer_guide.md'
      - 'user-guide/daq-api/DAQ_module_testing_guide.md'
    - Server:
      - Elasticsearch: 'user-guide/server/elasticsearch.md'
      - Rule Engine: 'user-guide/server/rule-engine.md'
      - Database: 'user-guide/server/database.md'
  - Appendices:
    - 'appendices/database_structure.md'

markdown_extensions:
  - toc:
      permalink: True
  - admonition
