site_name: C2MON
site_url: http://cern.ch/c2mon
docs_dir: ./src
site_dir: ./target

theme: mkdocs

repo_url: https://gitlab.cern.ch/c2mon/c2mon
repo_name: CERN GitLab
edit_uri: blob/master/docs/src/

extra_css:
    - css/extra.css

pages:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Overview:
    - 'Introduction to C2MON': 'overview/index.md'
    #- Core Concepts:
    #  - 'overview/index.md'
    - 'Process/Equipment': 'overview/process-equipment.md'
    - 'overview/tags.md'
    - 'overview/supervision.md'
    - 'overview/alarms.md'
    - 'Class/Device/Property': 'overview/class-device-property.md'
  - User Guide:
    - Client API:
      - Data Subscription: 'user-guide/client-api/index.md'
      - 'user-guide/client-api/configuration.md'
      - 'user-guide/client-api/history.md'
    - Server:
      - Running the server: 'user-guide/server/index.md'
      - Elasticsearch: 'user-guide/server/elasticsearch.md'
      - Rule Engine: 'user-guide/server/rule-engine.md'
      - Database: 'user-guide/server/database.md'
    - DAQ API:
      - General Overview: 'user-guide/daq-api/index.md'
      - 'user-guide/daq-api/DAQ_module_developer_guide.md'
      - 'user-guide/daq-api/DAQ_module_testing_guide.md'
  - About:
    - 'about/CHANGELOG.md'
    - Contributing: 'about/CONTRIBUTING.md'
    - 'about/license.md'


markdown_extensions:
  - toc:
      permalink: True
  - admonition
